version: "3.9"
services: 
  stat-961:
    build: .
    image: kuangda/stat-961
    ports: 
      - "8787:8787"
    environment: 
      - ROOT=TRUE
      - PASSWORD=chad
      - DISABLE_AUTH=true
    volumes: 
      - .:/home/rstudio